FROM ubuntu
RUN apt-get -y update 
new
===

RUN apt-get -y install openjdk-8-jdk wget
RUN mkdir /opt/tomcat
# COPY tomcat-8.5.37.tar.gz /tmp
# RUN cd /tmp && tar xvfz tomcat-8.5.37.tar.gz
# RUN mv /tmp/apache-tomcat-8.5.37/* /opt/tomcat/
# RUN rm /tmp/tomcat-8.5.37.tar.gz
ADD tomcat-8.5.37.tar.gz /tmp
RUN mv /tmp/apache-tomcat-8.5.37/* /opt/tomcat/
COPY myapp.war /opt/tomcat/webapps
EXPOSE 8080
ENTRYPOINT ["/opt/tomcat/bin/catalina.sh", "run"]  ## JSON Format
# ENTRYPOINT /opt/tomcat/bin/catalina.sh run  ## Shell Format











To convert above docker file into docker image ;
---------------------------------------------
docker build -t raviapp  -f new ../code/
raviapp--> app name , we can give any name
new --> docker filename
../code --> coping data from code path(i.e here copying myapp.war file from images directory )
